
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmeprulxppvsavgygplq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtZXBydWx4cHB2c2F2Z3lncGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTAzMTcsImV4cCI6MjA1OTkyNjMxN30.tr1-ulU5GcmZDLopcb5o58TXvESLJEbN8UyawsZP3x0";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storage: localStorage
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);

// Set up enhanced debug logging for authentication events
supabase.auth.onAuthStateChange((event, session) => {
  console.log("Supabase auth event:", event, session?.user?.id);
  
  // Additional debugging data
  if (event === 'SIGNED_IN') {
    console.log("User signed in successfully");
  } else if (event === 'SIGNED_OUT') {
    console.log("User signed out");
  } else if (event === 'TOKEN_REFRESHED') {
    console.log("Auth token refreshed");
  } else if (event === 'USER_UPDATED') {
    console.log("User data updated");
  }
});
